package ekg.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Arrays;

@Controller
public class LoginController {

    //mapping endpoint for standard entry
    @GetMapping("/")
    public String redirectShowLogin() {
        return "/login";
    }

    @GetMapping("/login")
    public String showLogin() {
        return "/login";
    }


    //checking for essential data and reading password form file to confirm login
    @GetMapping("/login-check")
    public String checkPassword1(@RequestParam("password") String password,
                                 @RequestParam("method") int method
    ) {

        //checking password from file generated by python script if wrong redirect back to login-view

        if (!password.isEmpty()) {
            String pass;
            try {
                FileReader fr = new FileReader("config.txt");
                BufferedReader br = new BufferedReader(fr);
                pass = br.readLine();
                if (!pass.equals(password)) return "forward:/login";
            } catch (Exception e) {
                System.out.println(Arrays.toString(e.getStackTrace()));
            }

            //sending to chosen endpoint: 1 for selection user view || 2 for create new user

            return switch (method) {
                case 1 -> "forward:/user_selection";
                case 2 -> "forward:/create_user";
                default -> "/login";
            };
        }
        return "forward:/login";
    }


}
